<?php

namespace TrekSt\Modules\ProductsAttributes\Models;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
use Spatie\Translatable\HasTranslations;

class ProductsAttribute extends Model
{
    use Sortable;
    use HasTranslations;

    public $fillable = ['group_id','type','title','description','name','order','published'];
    protected $table = 'products_attributes';
    protected $primaryKey = 'id';
    public $translatable = ['title', 'description'];

    public function values(){
        return $this->hasMany(ProductsProductAttributePivot::class,'product_attribute_id');
    }
    public function delete()
    {
        $this->values()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
