<?php

namespace TrekSt\Modules\ProductsAttributes\Models;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
use Spatie\Translatable\HasTranslations;

class ProductsAttributesGroup extends Model
{
    use Sortable;
    use HasTranslations;
    protected $table = 'products_attributes_groups';
    protected $primaryKey = 'id';
    public $fillable = ['title','description','name','order','published'];
    public $translatable = ['title', 'description'];


    public function productAttributes(){
        return $this->hasMany(ProductsAttribute::class,'group_id');
    }

    public function attributes(){
        return $this->hasMany(ProductsAttribute::class,'group_id');
    }
    public function delete()
    {
        foreach ($this->productAttributes as $item){
            $item->delete();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
